services :
  db : 
    image : postgres:17
    environment :
      POSTGRES_USER : tanstack
      POSTGRES_PASSWORD : tanstack
      POSTGRES_DB : tanstack
    ports :
      - "5433:5432"
    volumes :
      - ./.data:/var/lib/postgresql/data