/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteRouteImport } from './routes/_authed/dashboard/route'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedDashboardTodosIndexRouteImport } from './routes/_authed/dashboard/todos/index'
import { Route as AuthedDashboardCategoryIndexRouteImport } from './routes/_authed/dashboard/category/index'
import { Route as AuthedDashboardTodosCreateRouteImport } from './routes/_authed/dashboard/todos/create'
import { Route as AuthedDashboardCategoryCreateRouteImport } from './routes/_authed/dashboard/category/create'
import { Route as AuthedDashboardTodosIdEditRouteImport } from './routes/_authed/dashboard/todos/$id/edit'
import { Route as AuthedDashboardCategoryIdEditRouteImport } from './routes/_authed/dashboard/category/$id/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRouteRoute = AuthedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardTodosIndexRoute =
  AuthedDashboardTodosIndexRouteImport.update({
    id: '/todos/',
    path: '/todos/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardCategoryIndexRoute =
  AuthedDashboardCategoryIndexRouteImport.update({
    id: '/category/',
    path: '/category/',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardTodosCreateRoute =
  AuthedDashboardTodosCreateRouteImport.update({
    id: '/todos/create',
    path: '/todos/create',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardCategoryCreateRoute =
  AuthedDashboardCategoryCreateRouteImport.update({
    id: '/category/create',
    path: '/category/create',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardTodosIdEditRoute =
  AuthedDashboardTodosIdEditRouteImport.update({
    id: '/todos/$id/edit',
    path: '/todos/$id/edit',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)
const AuthedDashboardCategoryIdEditRoute =
  AuthedDashboardCategoryIdEditRouteImport.update({
    id: '/category/$id/edit',
    path: '/category/$id/edit',
    getParentRoute: () => AuthedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/category/create': typeof AuthedDashboardCategoryCreateRoute
  '/dashboard/todos/create': typeof AuthedDashboardTodosCreateRoute
  '/dashboard/category/': typeof AuthedDashboardCategoryIndexRoute
  '/dashboard/todos/': typeof AuthedDashboardTodosIndexRoute
  '/dashboard/category/$id/edit': typeof AuthedDashboardCategoryIdEditRoute
  '/dashboard/todos/$id/edit': typeof AuthedDashboardTodosIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/category/create': typeof AuthedDashboardCategoryCreateRoute
  '/dashboard/todos/create': typeof AuthedDashboardTodosCreateRoute
  '/dashboard/category': typeof AuthedDashboardCategoryIndexRoute
  '/dashboard/todos': typeof AuthedDashboardTodosIndexRoute
  '/dashboard/category/$id/edit': typeof AuthedDashboardCategoryIdEditRoute
  '/dashboard/todos/$id/edit': typeof AuthedDashboardTodosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/category/create': typeof AuthedDashboardCategoryCreateRoute
  '/_authed/dashboard/todos/create': typeof AuthedDashboardTodosCreateRoute
  '/_authed/dashboard/category/': typeof AuthedDashboardCategoryIndexRoute
  '/_authed/dashboard/todos/': typeof AuthedDashboardTodosIndexRoute
  '/_authed/dashboard/category/$id/edit': typeof AuthedDashboardCategoryIdEditRoute
  '/_authed/dashboard/todos/$id/edit': typeof AuthedDashboardTodosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/category/create'
    | '/dashboard/todos/create'
    | '/dashboard/category/'
    | '/dashboard/todos/'
    | '/dashboard/category/$id/edit'
    | '/dashboard/todos/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/category/create'
    | '/dashboard/todos/create'
    | '/dashboard/category'
    | '/dashboard/todos'
    | '/dashboard/category/$id/edit'
    | '/dashboard/todos/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/dashboard'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/category/create'
    | '/_authed/dashboard/todos/create'
    | '/_authed/dashboard/category/'
    | '/_authed/dashboard/todos/'
    | '/_authed/dashboard/category/$id/edit'
    | '/_authed/dashboard/todos/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/todos/': {
      id: '/_authed/dashboard/todos/'
      path: '/todos'
      fullPath: '/dashboard/todos/'
      preLoaderRoute: typeof AuthedDashboardTodosIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/category/': {
      id: '/_authed/dashboard/category/'
      path: '/category'
      fullPath: '/dashboard/category/'
      preLoaderRoute: typeof AuthedDashboardCategoryIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/todos/create': {
      id: '/_authed/dashboard/todos/create'
      path: '/todos/create'
      fullPath: '/dashboard/todos/create'
      preLoaderRoute: typeof AuthedDashboardTodosCreateRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/category/create': {
      id: '/_authed/dashboard/category/create'
      path: '/category/create'
      fullPath: '/dashboard/category/create'
      preLoaderRoute: typeof AuthedDashboardCategoryCreateRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/todos/$id/edit': {
      id: '/_authed/dashboard/todos/$id/edit'
      path: '/todos/$id/edit'
      fullPath: '/dashboard/todos/$id/edit'
      preLoaderRoute: typeof AuthedDashboardTodosIdEditRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/category/$id/edit': {
      id: '/_authed/dashboard/category/$id/edit'
      path: '/category/$id/edit'
      fullPath: '/dashboard/category/$id/edit'
      preLoaderRoute: typeof AuthedDashboardCategoryIdEditRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
  }
}

interface AuthedDashboardRouteRouteChildren {
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardCategoryCreateRoute: typeof AuthedDashboardCategoryCreateRoute
  AuthedDashboardTodosCreateRoute: typeof AuthedDashboardTodosCreateRoute
  AuthedDashboardCategoryIndexRoute: typeof AuthedDashboardCategoryIndexRoute
  AuthedDashboardTodosIndexRoute: typeof AuthedDashboardTodosIndexRoute
  AuthedDashboardCategoryIdEditRoute: typeof AuthedDashboardCategoryIdEditRoute
  AuthedDashboardTodosIdEditRoute: typeof AuthedDashboardTodosIdEditRoute
}

const AuthedDashboardRouteRouteChildren: AuthedDashboardRouteRouteChildren = {
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardCategoryCreateRoute: AuthedDashboardCategoryCreateRoute,
  AuthedDashboardTodosCreateRoute: AuthedDashboardTodosCreateRoute,
  AuthedDashboardCategoryIndexRoute: AuthedDashboardCategoryIndexRoute,
  AuthedDashboardTodosIndexRoute: AuthedDashboardTodosIndexRoute,
  AuthedDashboardCategoryIdEditRoute: AuthedDashboardCategoryIdEditRoute,
  AuthedDashboardTodosIdEditRoute: AuthedDashboardTodosIdEditRoute,
}

const AuthedDashboardRouteRouteWithChildren =
  AuthedDashboardRouteRoute._addFileChildren(AuthedDashboardRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRouteRoute: AuthedDashboardRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
