on:
  push: 
    branches: 
     - main

  jobs: 
    test-cicd:
      runs-on: ubuntu-latest
      steps:
        - uses : actions/checkout@v6
        - uses : actions/setup-node@v6
          with:
           node-version: 24
        - name : Setup PNPM
          run: npm install -g pnpm@latest
        - name: Setup Dependency
          run: pnpm install --frozen-lockfile
        

  